# Generated by Django 5.2.11 on 2026-03-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('so_giay_to', models.CharField(max_length=30, unique=True, verbose_name='Số CMND/CCCD/MST')),
                ('loai_doi_tuong', models.CharField(choices=[('ca_nhan', 'Cá nhân'), ('to_chuc', 'Tổ chức'), ('ho_gia_dinh', 'Hộ gia đình')], default='ca_nhan', max_length=20, verbose_name='Loại đối tượng')),
                ('dia_chi', models.TextField(blank=True, verbose_name='Địa chỉ liên lạc')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chủ sử dụng đất',
                'verbose_name_plural': 'Danh sách chủ sử dụng đất',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='NhatKyPhanTich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_phan_tich', models.CharField(max_length=200, verbose_name='Tên phân tích')),
                ('loai_phan_tich', models.CharField(choices=[('buffer', 'Vùng đệm (Buffer)'), ('intersect', 'Giao thoa (Intersect)'), ('distance', 'Khoảng cách (Distance)'), ('overlay', 'Chồng lớp (Overlay)')], max_length=20, verbose_name='Loại phân tích')),
                ('tham_so_dau_vao', models.JSONField(default=dict, verbose_name='Tham số đầu vào')),
                ('ket_qua', models.JSONField(default=dict, verbose_name='Kết quả phân tích')),
                ('nguoi_thuc_hien', models.CharField(blank=True, max_length=100, verbose_name='Người thực hiện')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký phân tích GIS',
                'verbose_name_plural': 'Nhật ký phân tích GIS',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='VungQuyHoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vung', models.CharField(max_length=200, verbose_name='Tên vùng quy hoạch')),
                ('loai_quy_hoach', models.CharField(choices=[('dat_o', 'Đất ở'), ('dat_thuong_mai', 'Đất thương mại dịch vụ'), ('dat_cong_nghiep', 'Đất công nghiệp'), ('dat_cong_cong', 'Đất công cộng'), ('dat_giao_thong', 'Đất giao thông'), ('dat_cay_xanh', 'Đất cây xanh'), ('dat_nong_nghiep', 'Đất nông nghiệp bảo vệ'), ('dat_du_lich', 'Đất du lịch')], max_length=50, verbose_name='Loại quy hoạch')),
                ('nam_quy_hoach', models.IntegerField(verbose_name='Năm quy hoạch')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('geojson', models.TextField(blank=True, verbose_name='Dữ liệu GeoJSON')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vùng quy hoạch',
                'verbose_name_plural': 'Danh sách vùng quy hoạch',
            },
        ),
        migrations.CreateModel(
            name='ThuaDat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thua', models.CharField(max_length=50, unique=True, verbose_name='Mã thửa đất')),
                ('so_to', models.IntegerField(verbose_name='Số tờ bản đồ')),
                ('so_thua', models.IntegerField(verbose_name='Số thửa')),
                ('dia_chi_thua', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ thửa đất')),
                ('dien_tich', models.FloatField(verbose_name='Diện tích (m²)')),
                ('loai_dat', models.CharField(choices=[('ODT', 'Đất ở đô thị'), ('ONT', 'Đất ở nông thôn'), ('CLN', 'Đất cây lâu năm'), ('LUA', 'Đất trồng lúa'), ('TSC', 'Đất trụ sở cơ quan'), ('DGT', 'Đất giao thông'), ('SKC', 'Đất sản xuất kinh doanh'), ('DDT', 'Đất phi nông nghiệp khác')], max_length=10, verbose_name='Loại đất')),
                ('muc_dich_su_dung', models.CharField(blank=True, max_length=200, verbose_name='Mục đích sử dụng')),
                ('vi_do', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('kinh_do', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('geojson', models.TextField(blank=True, verbose_name='Dữ liệu GeoJSON')),
                ('so_gcn', models.CharField(blank=True, max_length=100, verbose_name='Số Giấy chứng nhận')),
                ('ngay_cap_gcn', models.DateField(blank=True, null=True, verbose_name='Ngày cấp GCN')),
                ('thoi_han_su_dung', models.DateField(blank=True, null=True, verbose_name='Thời hạn sử dụng')),
                ('that_nghiep_lau', models.BooleanField(default=False, verbose_name='Có tranh chấp')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('chu_su_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thua_dat', to='myapp.chusudung', verbose_name='Chủ sử dụng')),
            ],
            options={
                'verbose_name': 'Thửa đất',
                'verbose_name_plural': 'Danh sách thửa đất',
                'ordering': ['so_to', 'so_thua'],
            },
        ),
        migrations.CreateModel(
            name='CanhBaoGIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề cảnh báo')),
                ('loai_canh_bao', models.CharField(choices=[('vi_pham_quy_hoach', 'Vi phạm quy hoạch'), ('tranh_chap', 'Tranh chấp ranh giới'), ('that_lac_ho_so', 'Thiếu hồ sơ'), ('sap_het_han', 'Sắp hết thời hạn GCN'), ('canh_bao_gis', 'Cảnh báo từ phân tích GIS')], max_length=30, verbose_name='Loại cảnh báo')),
                ('muc_do', models.CharField(choices=[('thap', 'Thấp'), ('trung_binh', 'Trung bình'), ('cao', 'Cao'), ('khan_cap', 'Khẩn cấp')], default='trung_binh', max_length=20, verbose_name='Mức độ')),
                ('noi_dung', models.TextField(verbose_name='Nội dung chi tiết')),
                ('vi_do', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('kinh_do', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('da_xu_ly', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('ngay_phat_sinh', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phát sinh')),
                ('ngay_xu_ly', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('thua_dat_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canh_bao', to='myapp.thuadat', verbose_name='Thửa đất liên quan')),
            ],
            options={
                'verbose_name': 'Cảnh báo GIS',
                'verbose_name_plural': 'Danh sách cảnh báo',
                'ordering': ['-ngay_phat_sinh'],
            },
        ),
        migrations.CreateModel(
            name='BienDongDat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_bien_dong', models.CharField(choices=[('chuyen_nhuong', 'Chuyển nhượng'), ('tang_cho', 'Tặng cho'), ('the_chap', 'Thế chấp'), ('tach_thua', 'Tách thửa'), ('hop_thua', 'Hợp thửa'), ('doi_muc_dich', 'Đổi mục đích sử dụng'), ('thu_hoi', 'Thu hồi đất')], max_length=30, verbose_name='Loại biến động')),
                ('ngay_bien_dong', models.DateField(verbose_name='Ngày biến động')),
                ('so_van_ban', models.CharField(blank=True, max_length=100, verbose_name='Số văn bản')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('nguoi_ghi_nhan', models.CharField(blank=True, max_length=100, verbose_name='Người ghi nhận')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('chu_cu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bien_dong_cu', to='myapp.chusudung', verbose_name='Chủ cũ')),
                ('chu_moi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bien_dong_moi', to='myapp.chusudung', verbose_name='Chủ mới')),
                ('thua_dat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_dong', to='myapp.thuadat', verbose_name='Thửa đất')),
            ],
            options={
                'verbose_name': 'Biến động đất đai',
                'verbose_name_plural': 'Lịch sử biến động',
                'ordering': ['-ngay_bien_dong'],
            },
        ),
    ]
