# Generated by Django 5.2.11 on 2026-04-12 11:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuadat',
            name='geojson',
        ),
        migrations.RemoveField(
            model_name='thuadat',
            name='kinh_do',
        ),
        migrations.RemoveField(
            model_name='thuadat',
            name='loai_dat',
        ),
        migrations.RemoveField(
            model_name='thuadat',
            name='vi_do',
        ),
        migrations.RemoveField(
            model_name='vungquyhoach',
            name='geojson',
        ),
        migrations.AddField(
            model_name='thuadat',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Tọa độ Trung tâm'),
        ),
        migrations.AddField(
            model_name='thuadat',
            name='geojson_old',
            field=models.TextField(blank=True, verbose_name='Dữ liệu GeoJSON (Cũ)'),
        ),
        migrations.AddField(
            model_name='thuadat',
            name='loai_dat_hien_trang',
            field=models.CharField(choices=[('ODT', 'Đất ở đô thị'), ('ONT', 'Đất ở nông thôn'), ('CLN', 'Đất cây lâu năm'), ('LUA', 'Đất trồng lúa'), ('TSC', 'Đất trụ sở cơ quan'), ('DGT', 'Đất giao thông'), ('SKC', 'Đất sản xuất kinh doanh'), ('DDT', 'Đất phi nông nghiệp khác')], default='ODT', max_length=10, verbose_name='Loại đất hiện trạng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thuadat',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Dữ liệu Không gian (MultiPolygon)'),
        ),
        migrations.AddField(
            model_name='vungquyhoach',
            name='geojson_old',
            field=models.TextField(blank=True, verbose_name='Dữ liệu GeoJSON (Cũ)'),
        ),
        migrations.AddField(
            model_name='vungquyhoach',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Vùng Không gian'),
        ),
        migrations.AddField(
            model_name='vungquyhoach',
            name='loai_dat_quy_hoach',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chỉ tiêu Sử dụng đất'),
        ),
        migrations.AddField(
            model_name='vungquyhoach',
            name='muc_do_nghiem_trong',
            field=models.CharField(choices=[('thap', 'Thấp'), ('cao', 'Cao')], default='thap', max_length=20, verbose_name='Mức độ Nghiêm trọng'),
        ),
    ]
