# Generated by Django 5.2.11 on 2026-04-12 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_thuadat_geojson_remove_thuadat_kinh_do_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canhbaogis',
            name='kinh_do',
        ),
        migrations.RemoveField(
            model_name='canhbaogis',
            name='vi_do',
        ),
        migrations.AddField(
            model_name='canhbaogis',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Vị trí'),
        ),
    ]
