# Generated by Django 5.2.11 on 2026-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_canhbaogis_kinh_do_remove_canhbaogis_vi_do_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thuadat',
            unique_together={('so_to', 'so_thua')},
        ),
        migrations.RemoveField(
            model_name='vungquyhoach',
            name='geojson_old',
        ),
        migrations.AddField(
            model_name='thuadat',
            name='co_tranh_chap',
            field=models.BooleanField(default=False, verbose_name='Có tranh chấp'),
        ),
        migrations.AlterField(
            model_name='thuadat',
            name='dien_tich',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Diện tích (m²)'),
        ),
        migrations.RemoveField(
            model_name='thuadat',
            name='geojson_old',
        ),
        migrations.RemoveField(
            model_name='thuadat',
            name='that_nghiep_lau',
        ),
    ]
