# Generated by Django 5.2.11 on 2026-04-12 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_thuadat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thuadat',
            name='chu_su_dung',
        ),
        migrations.AddField(
            model_name='thuadat',
            name='danh_sach_chu_su_dung',
            field=models.ManyToManyField(blank=True, related_name='thua_dat', to='myapp.chusudung', verbose_name='Danh sách Chủ sử dụng'),
        ),
        migrations.AlterField(
            model_name='chusudung',
            name='so_giay_to',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Giấy tờ không hợp lệ. Phải từ 9-15 ký tự chữ/số.', regex='^[a-zA-Z0-9-]{9,15}$')], verbose_name='Số CMND/CCCD/MST'),
        ),
    ]
