# Generated by Django 5.2.11 on 2026-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_thuadat_chu_su_dung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendongdat',
            name='gia_tri_giao_dich',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Giá trị giao dịch (VNĐ)'),
        ),
        migrations.AddField(
            model_name='biendongdat',
            name='tai_lieu_dinh_kem',
            field=models.FileField(blank=True, null=True, upload_to='tai_lieu_bien_dong/', verbose_name='Tài liệu đính kèm'),
        ),
        migrations.AddField(
            model_name='biendongdat',
            name='trang_thai',
            field=models.CharField(choices=[('dang_xu_ly', 'Đang xử lý'), ('hoan_tat', 'Hoàn tất'), ('huy', 'Hủy')], default='dang_xu_ly', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
