# Generated by Django 5.2.11 on 2026-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_biendongdat_gia_tri_giao_dich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vungquyhoach',
            name='dien_tich',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Diện tích (m²)'),
        ),
    ]
