# Generated by Django 5.2.11 on 2026-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vungquyhoach_dien_tich'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuadat',
            name='dien_tich_quy_hoach',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diện tích thuộc quy hoạch (m²)'),
        ),
        migrations.AddField(
            model_name='thuadat',
            name='nguon_goc_su_dung',
            field=models.TextField(blank=True, verbose_name='Nguồn gốc sử dụng đất'),
        ),
    ]
