# Generated by Django 5.2.11 on 2026-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_thuadat_dien_tich_quy_hoach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vungquyhoach',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
