# Generated by Django 5.2.11 on 2026-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vungquyhoach_ngay_cap_nhat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canhbaogis',
            name='da_xu_ly',
        ),
        migrations.AddField(
            model_name='canhbaogis',
            name='trang_thai',
            field=models.CharField(choices=[('chua_xu_ly', 'Chưa xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_hoan_tat', 'Đã xử lý xong')], default='chua_xu_ly', max_length=20, verbose_name='Trạng thái xử lý'),
        ),
    ]
