# Generated by Django 5.2.11 on 2026-04-16 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_canhbaogis_da_xu_ly_canhbaogis_trang_thai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDungProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('vai_tro', models.CharField(choices=[('admin', 'Quản trị viên'), ('can_bo', 'Cán bộ'), ('nguoi_dung', 'Người dùng')], default='nguoi_dung', max_length=20, verbose_name='Vai trò')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Đang bị khóa')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
