# Generated by Django 5.2.11 on 2026-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_nguoidungprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidungprofile',
            name='khu_vuc_phu_trach',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Khu vực phụ trách'),
        ),
    ]
